# Configurações do ambiente de PRODUÇÃO
server.port=8080

# Banco de dados de Produção (ex: na nuvem)
spring.datasource.url=${PROD_DB_URL} # Usando variável de ambiente é mais seguro
spring.datasource.username=${PROD_DB_USER}
spring.datasource.password=${PROD_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate # Mais seguro para produção

# Origens permitidas para CORS em PROD (URL do seu frontend)
cors.allowed-origins=https://www.seu-frontend.com

# Configurações do JWT para PROD (use uma chave secreta mais forte e guarde-a como variável de ambiente)
jwt.secret=${JWT_SECRET_PROD}
jwt.expiration=86400000 # 24 horas